version: '3.8'

services:
  nlweb-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ENDPOINT=https://api.openai.com/v1/chat/completions
      - NLWEB_LOGGING_PROFILE=production
      - PORT=8000
    volumes:
      - ./data:/app/data
      - ./logs:/app/code/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add Qdrant service if you want to run Qdrant in Docker too
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333" 
  #   volumes:
  #     - ./qdrant_data:/qdrant/storage
  #   restart: unless-stopped
